[variables]
NIXPACKS_PYTHON_VERSION = "3.11"

[phases.setup]
nixPkgs = ["nodejs_20", "ffmpeg"]

[phases.install]
cmds = [
  "npm install",
  "python -m ensurepip --upgrade",
  "pip install yt-dlp"
]

[start]
cmd = "node server.js"
